#1 configuration/base.yaml 

application:
  port: 8000
  hmac_secret: "super-long-and-secret_random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
    base_url: "localhost"
    sender_email: "gustavoantonio51@gmail.com"
    sendgrid_api_key: "sendgridtoken"
    timeout_milliseconds: 10000
